apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dappest-cluster-co
spec:
  secretName: dappest-cluster-co-tls
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  commonName: '*.dappest.co'
  dnsNames:
  - dappest.co
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - '*.dappest.co'
      - dappest.co
