apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brian@dappest.co
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    dns01:
      providers:
      - name: prod-dns
        route53:
          region: us-east-1
          accessKeyID: 
          secretAccessKeySecretRef:
            name: acme-route53
            key: acme-route53-access-key