apiVersion: v1
kind: Service
metadata:
  name: dappest-celery-beat
  labels:
    role: dappest-celery-beat
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: http
    name: http
  selector:
    role: dappest-celery-beat
  type: ClusterIP