apiVersion: v1
data:
  .dockerconfigjson:
kind: Secret
metadata:
  name: dappest-docker-cred
  selfLink: /api/v1/namespaces/development/secrets/dappest-docker-cred
type: kubernetes.io/dockerconfigjson
